# Generated by Django 5.1.2 on 2024-10-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
