# Generated by Django 5.1.2 on 2024-10-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_is_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(to='jobs.jobcategory'),
        ),
    ]
